version: '3'
services:
  askfp:
    build: ./askfp
    image: ruby:2.6.3
    container_name: askfp
    hostname: docker_askfp
    ports:
     - "3000:3000"
    networks:
      askfp_net:
        ipv4_address: 172.20.0.2
    volumes:
     - /Users/kazukimorokado/workspace/askfp/askfp/:/home/git/askfp/:z
    depends_on:
     - mysqldb
    tty: true
    restart: always
  mysqldb:
    build: ./mysql
    image: mysql:5.7
    container_name: mysqldb
    hostname: docker_mysqldb
    environment:
      MYSQL_DATABASE: askfp_development
      MYSQL_USER: askfp
      MYSQL_PASSWORD: askfp_password
      MYSQL_ROOT_PASSWORD: askfp_rootpassword
    ports:
     - "3306:3306"
    networks:
      askfp_net:
        ipv4_address: 172.20.0.3
    restart: always
networks:
  askfp_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.1/24
        # gateway: 172.20.0.1